language: node_js
node_js:
- '0.11'
- '0.10'
services:
- redis-server
script:
- npm run-script spec
- npm run-script test
notifications:
  slack:
    secure: UdU8wjFPMNzmvrFwgr7aSzpQGmP+YY0jOXC90K6vMY97mKmgScCjopzG00OryTYKzUpZkoa6L2G4LDcUlYWg1DIDg8qD91mQZUS42we1JAb76LCuTQ/0tbE9xQ62gCSBz19uFgUConvJQ8wzAtCiXNiiCBZ10Vj7ZlQ9YiPkZIU=
